// <auto-generated />
using System;
using GameOfDrones.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOfDrones.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GameOfDrones.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Player1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paper"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Scissors"
                        });
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.MoveRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilledMoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KillerMoveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KilledMoveId");

                    b.HasIndex("KillerMoveId");

                    b.ToTable("MoveRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KilledMoveId = 1,
                            KillerMoveId = 2
                        },
                        new
                        {
                            Id = 2,
                            KilledMoveId = 3,
                            KillerMoveId = 1
                        },
                        new
                        {
                            Id = 3,
                            KilledMoveId = 2,
                            KillerMoveId = 3
                        });
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player1MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("Player1MoveId");

                    b.HasIndex("Player2MoveId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Game", b =>
                {
                    b.HasOne("GameOfDrones.Api.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.MoveRule", b =>
                {
                    b.HasOne("GameOfDrones.Api.Models.Move", "KilledMove")
                        .WithMany()
                        .HasForeignKey("KilledMoveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Move", "KillerMove")
                        .WithMany("Kills")
                        .HasForeignKey("KillerMoveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KilledMove");

                    b.Navigation("KillerMove");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Round", b =>
                {
                    b.HasOne("GameOfDrones.Api.Models.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Move", "Player1Move")
                        .WithMany()
                        .HasForeignKey("Player1MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Move", "Player2Move")
                        .WithMany()
                        .HasForeignKey("Player2MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Player1Move");

                    b.Navigation("Player2Move");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Game", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Move", b =>
                {
                    b.Navigation("Kills");
                });
#pragma warning restore 612, 618
        }
    }
}
